.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. carboncoin_qt test_carboncoin_qt
clean: FORCE
	$(MAKE) -C .. carboncoin_qt_clean test_carboncoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_carboncoin_qt_check
carboncoin-qt carboncoin-qt.exe: FORCE
	 $(MAKE) -C .. carboncoin_qt
